Homework1 -- MADE
made-ml-in-prod-2022/tinctura13 pull request #1
Opened 2022-05-08 07:49 UTC by tinctura13

Привет!  
Делал на основе `ml_project_example` из лекции.  
Данные взяты здесь [Heart Disease Cleveland UCI](https://www.kaggle.com/datasets/cherngs/heart-disease-cleveland-uci) 
Два пайплайна пребодработки данных:  

- `One-Hot Encoding` для категориальных фич
- `Custom Transformer` для числовых (в качестве кастомного трансформера - Standard Scaler)  

С помощью гидры сделаны конфиги для моделей: 

- `LogReg` 
- `RandomForest`  

Инструкции для запуска в [README.md](https://github.com/made-ml-in-prod-2022/tinctura13/blob/homework1/ml_project/README.md)

Самооценка:  

0. ☑ В описании к пулл реквесту описаны основные "архитектурные" и тактические решения, которые сделаны в вашей работе. В общем, описание того, что именно вы сделали и для чего, чтобы вашим ревьюерам было легче понять ваш код (1 балл)
1. ☑ В пулл-реквесте проведена самооценка, распишите по каждому пункту выполнен ли критерий или нет и на сколько баллов(частично или полностью) (1 балл)
2. ☑ Выполнено EDA, закоммитьте ноутбук в папку с ноутбуками (1 балл) Вы так же можете построить в ноутбуке прототип(если это вписывается в ваш стиль работы) ☑ Можете использовать не ноутбук, а скрипт, который сгенерит отчет, закоммитьте и скрипт и отчет (за это + 1 балл)
3. ☐ Написана функция/класс для тренировки модели, вызов оформлен как утилита командной строки, записана в readme инструкцию по запуску (3 балла)
4. ☐ Написана функция/класс predict (вызов оформлен как утилита командной строки), которая примет на вход артефакт/ы от обучения, тестовую выборку (без меток) и запишет предикт по заданному пути, инструкция по вызову записана в readme (3 балла)
5. ☑ Проект имеет модульную структуру (2 балла)
6. ☑ Использованы логгеры (2 балла)
7. ☐ Написаны тесты на отдельные модули и на прогон обучения и predict (3 балла)
8. ☐ Для тестов генерируются синтетические данные, приближенные к реальным (2 балла)
9. ☑ Обучение модели конфигурируется с помощью конфигов в json или yaml, закоммитьте как минимум 2 корректные конфигурации, с помощью которых можно обучить модель (разные модели, стратегии split, preprocessing) (3 балла)
10. ☑ Используются датаклассы для сущностей из конфига, а не голые dict (2 балла)
11. ☑ Напишите кастомный трансформер и протестируйте его (3 балла)
12. ☑ В проекте зафиксированы все зависимости (1 балл)
13. ☐ Настроен CI для прогона тестов, линтера на основе github actions (3 балла). 
- ☑ Используйте hydra для конфигурирования (https://hydra.cc/docs/intro/) (3 балла)
Итого: 20 баллов

2022-05-23 19:29 UTC, SVizor42 commented on ml_project/train_pipeline.py
> +    return metrics
Если возвращаешь метрики, то следует указать return type

2022-05-23 19:31 UTC, SVizor42 commented on ml_project/train_pipeline.py
> +    serialize_transformer(transformer, params.output_transformer_path)
Признаки еще не преобразованы. Трансформер лучше сохранить позднее, можно в составе пайплайна

2022-05-23 19:33 UTC, SVizor42 commented on ml_project/visualize.py
> +from src.configs.train_params import (TrainingPipelineParams,
Старайся разделять импорты стандартных и локальных пакетов/модулей (см. pep-8)

2022-05-23 19:42 UTC, SVizor42 commented on ml_project/infer_pipeline.py
> +import sched
Не используется

2022-05-23 19:47 UTC, SVizor42 commented on ml_project/src/utils/utils.py
> +        "roc_auc_score": roc_auc_score(target, predictions),
Тут все-таки надо подавать скорее всего prob?

2022-05-23 19:55 UTC, SVizor42 requested changes
В целом, все хорошо. Пройдись по комментариям.

Еще добавлю:
- пункты 3 и 4 тоже выполнены
- у кастомного трансформера нет тестов
- я бы вынес функции из `utils.py` в модули модели, scaler также отправил бы в `models`
- добавил докстринги (на свое усмотрение)

2022-05-25 09:32 UTC, tinctura13 commented on ml_project/train_pipeline.py
> +    serialize_transformer(transformer, params.output_transformer_path)
Тут же я его подгоняю под данные и сохраняю для инфера, не понял зачем его позднее сохранять. На инфере я его загружаю, преобразую данные и отправляю в модель.

2022-05-25 09:32 UTC, tinctura13 commented on ml_project/train_pipeline.py
> +    return metrics
Пофиксил!

2022-05-25 09:33 UTC, tinctura13 commented on ml_project/visualize.py
> +from src.configs.train_params import (TrainingPipelineParams,
Пофиксил!

2022-05-25 09:33 UTC, tinctura13 commented on ml_project/infer_pipeline.py
> +import sched
Пофиксил!

2022-05-25 09:33 UTC, tinctura13 commented on ml_project/src/utils/utils.py
> +        "roc_auc_score": roc_auc_score(target, predictions),
Точно, для roc_auc нужно predict_proba, пофисил!

2022-05-25 09:37 UTC, merged

2022-05-25 10:10 UTC, SVizor42 commented
Ок.
**Сумма: 26 баллов**
На будущее - мерджить ветку нужно после аппрува. Если приходит запрос на изменения, то вносишь их / отвечаешь на комментарии и наживаешь Re-request review.

2022-05-25 12:08 UTC, tinctura13 commented
Да, сорян! Я что-то нажал и всё сломалось) Спасибо за советы и проверку, это мой первый пулл-реквест.